# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache ./.Xil/Vivado-6591-MIoT/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/raxt/CESE_Workspace/CLP_workspace/TPfinal/Sintesis/Transceiver.cache/wt [current_project]
set_property parent.project_path /home/raxt/CESE_Workspace/CLP_workspace/TPfinal/Sintesis/Transceiver.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:arty-z7-10:part0:1.1 [current_project]
set_property ip_output_repo /home/raxt/CESE_Workspace/CLP_workspace/TPfinal/Sintesis/Transceiver.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  /home/raxt/CESE_Workspace/CLP_workspace/TPfinal/Fuente/Implementacion/genEna.vhd
  /home/raxt/CESE_Workspace/CLP_workspace/TPfinal/Fuente/Implementacion/meta_harden.vhd
  /home/raxt/CESE_Workspace/CLP_workspace/TPfinal/Fuente/Receptor/receiver.vhd
  /home/raxt/CESE_Workspace/CLP_workspace/TPfinal/Fuente/Implementacion/receiver_impl.vhd
  /home/raxt/CESE_Workspace/CLP_workspace/TPfinal/Fuente/Transmisor/transmitter.vhd
  /home/raxt/CESE_Workspace/CLP_workspace/TPfinal/Fuente/Implementacion/transmitter_impl.vhd
  /home/raxt/CESE_Workspace/CLP_workspace/TPfinal/Fuente/Implementacion/transceiver_impl.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/raxt/CESE_Workspace/CLP_workspace/TPfinal/Fuente/Implementacion/ArtyZ7_10.xdc
set_property used_in_implementation false [get_files /home/raxt/CESE_Workspace/CLP_workspace/TPfinal/Fuente/Implementacion/ArtyZ7_10.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top transceriver_impl -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef transceriver_impl.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file transceriver_impl_utilization_synth.rpt -pb transceriver_impl_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
